version: '3.8'

volumes:
   nextcloud-html:
   nextcloud-apps:
   nextcloud-config:
   nextcloud-data:
   db:

services:
  nextcloud:
    image: nextcloud:latest
    volumes:
      - nextcloud-html:/var/www/html # main folder for nextcloud, needed for updating
      - nextcloud-apps:/var/www/html/custom_apps # where custom or modified nextcloud apps are stored
      - nextcloud-config:/var/www/html/config # local nextcloud configuration
      - nextcloud-data:/var/www/html/data # data for nextcloud, like uploaded files
    env_file: .nextcloud-env
    ports:
      - 8080:80
    depends_on:
      - mariadb
    restart: unless-stopped
  
  mariadb:
    image: mariadb:10.11
    env_file: .db-env
    command: --transaction-isolation=READ-COMMITTED  --log-bin=mysqld-bin --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7.0.5
    restart: unless-stopped



